[book]
authors = ["Martin Geisler", "adapted by Cristel Pelsser"]
language = "en"
multilingual = false
src = "src"
title = "Rust-LINFO2315 (adapted from Comprehensive Rust 🦀)"

[rust]
edition = "2021"

[build]
extra-watch-dirs = ["po"]

[preprocessor.links]
renderers = ["html"]

[preprocessor.index]
renderers = ["html"]

[preprocessor.svgbob]
renderers = ["html"]
class = "bob"

# Enable this preprocessor to overlay a large red rectangle on the
# pages. This will show you an estimate of what the course
# participants can see during the presentation.
#
# [preprocessor.aspect-ratio-helper]
# command = "./aspect-ratio-helper.py"

[output.html]
curly-quotes = true
additional-js = ["ga4.js", "speaker-notes.js"]
additional-css = ["svgbob.css", "speaker-notes.css"]
site-url = "/rust-linfo2315/"
git-repository-url = "https://github.com/cpelsser/rust-mdbook"
edit-url-template = "https://github.com/cpelsser/rust-mdbook/edit/main/{path}"

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true
